import { Info, Download } from "lucide-react";
import { FaGithub, FaLinkedin, FaGlobe } from "react-icons/fa";
import { HiArrowLeft } from "react-icons/hi";

import { Button } from "@/components/ui/button";
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogClose,
	DialogHeader,
	DialogTitle,
	DialogTrigger,
} from "@/components/ui/dialog";

export function AppInfoDialog() {
	return (
		<Dialog>
			<DialogTrigger asChild>
				<Button variant="outline" size="icon">
					<Info className="h-[1.2rem] w-[1.2rem]" />
					<span className="sr-only">App Info</span>
				</Button>
			</DialogTrigger>

			{/* Dialog Content */}
			<DialogContent className="sm:max-w-md">
				<DialogHeader>
					<DialogTitle className="text-center text-3xl">
						About This App
					</DialogTitle>
					<DialogDescription>
						Learn how to use the RBR Inventory Formatter.
					</DialogDescription>
				</DialogHeader>
				<div className="space-y-4">
					{/* Instructions */}
					<section>
						<h3 className="text-lg font-semibold">Instructions</h3>
						<ol className="list-decimal list-inside space-y-2 text-muted-foreground">
							<li>
								Upload an{" "}
								<code className="bg-muted text-accent-foreground px-1 rounded">
									.xls
								</code>{" "}
								file generated by the Alma library system.
							</li>
							<li>
								Customize preferences to remove unnecessary columns and add
								inventory data like initials or dates.
							</li>
							<li>
								Download the processed{" "}
								<code className="bg-muted text-accent-foreground px-1 rounded">
									.xlsx
								</code>{" "}
								file, ready for printing.
							</li>
						</ol>
					</section>

					{/* Test File Download */}
					<section>
						<h3 className="text-lg font-semibold">Test File</h3>
						<p className="text-muted-foreground">
							Try the app using this sample file:
						</p>
						<Button
							variant="outline"
							className="flex items-center space-x-2 mt-2"
							asChild
						>
							<a href="/reading-list-example.xls" download>
								<Download className="h-4 w-4" />
								<span>Download Test File</span>
							</a>
						</Button>
					</section>

					{/* Credits */}
					<section>
						<h3 className="text-lg font-semibold text-accent-foreground">
							Credits
						</h3>
						<p className="text-muted-foreground mb-3">
							Designed and developed by{" "}
							<a
								href="https://www.edwinperaza.com"
								target="_blank"
								rel="noopener noreferrer"
								className="text-green-500 hover:text-green-600 transition-colors"
							>
								Edwin Peraza
							</a>{" "}
							for Circ.
						</p>

						<div className="flex space-x-6 w-full justify-around">
							<a
								href="https://github.com/edwinperaza99"
								target="_blank"
								rel="noopener noreferrer"
								className="flex items-center space-x-2 text-muted-foreground hover:text-accent-foreground transition-colors"
							>
								<FaGithub className="h-5 w-5" />
								<span>GitHub</span>
							</a>
							<a
								href="https://www.linkedin.com/in/edwin-peraza/"
								target="_blank"
								rel="noopener noreferrer"
								className="flex items-center space-x-2 text-muted-foreground hover:text-accent-foreground transition-colors"
							>
								<FaLinkedin className="h-5 w-5" />
								<span>LinkedIn</span>
							</a>
							<a
								href="https://www.edwinperaza.com"
								target="_blank"
								rel="noopener noreferrer"
								className="flex items-center space-x-2 text-muted-foreground hover:text-accent-foreground transition-colors"
							>
								<FaGlobe className="h-5 w-5" />
								<span>Portfolio</span>
							</a>
						</div>
					</section>
				</div>
				<DialogFooter>
					<DialogClose asChild>
						<Button type="button" className="w-full">
							<HiArrowLeft className="h-5 w-5" />
							<span>Back to App</span>
						</Button>
					</DialogClose>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}
